[build]
  command = "pnpm install && pnpm build"
  publish = ".netlify/output/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_BUILD_DEBUG = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
